### ISSUE TITLE
Error missing config file when running

### ISSUE THREAD

**Issue by pauldeden** [byu-oit-appdev/handel-codepipeline#25]
Here's what I did and what happened.
```
pauldeden:~/workspace (newawesomer) $ handel-codepipeline 
info: Welcome to the Handel CodePipeline setup wizard
? Please enter the name of the pipeline from your handel-codepipeline.yml file that you would like to create prd
? Please enter the name of the account where your pipeline will be created prd-billing-oit-byu
? Please enter the path to the directory containing the Handel account configuration files /home/ubuntu/handel-account-configs
error: Error setting up Handel CodePipeline: Error: ENOENT: no such file or directory, open '/home/ubuntu/.handel-codepipeline/config.yml'
error:  Error: ENOENT: no such file or directory, open '/home/ubuntu/.handel-codepipeline/config.yml'
    at Error (native)
    at Object.fs.openSync (fs.js:641:18)
    at Object.fs.writeFileSync (fs.js:1347:33)
    at Object.exports.saveYamlFile (/home/ubuntu/.nvm/versions/node/v6.10.3/lib/node_modules/handel-codepipeline/lib/util/util.js:66:19)
    at cacheAccountConfigsPath (/home/ubuntu/.nvm/versions/node/v6.10.3/lib/node_modules/handel-codepipeline/lib/input/index.js:60:14)
    at inquirer.prompt.then.answers (/home/ubuntu/.nvm/versions/node/v6.10.3/lib/node_modules/handel-codepipeline/lib/input/index.js:104:17)
```

**Comment by pauldeden** [comment]
I was running this against https://github.com/byu-oit-appdev/aws-accounts-to-cmdb

**Comment by pauldeden** [comment]
More info

```
pauldeden:~/workspace (newawesomer) $ npm --version
3.10.10
pauldeden:~/workspace (newawesomer) $ node --version
v6.10.3

**Comment by pauldeden** [comment]
I already created account config [here](https://github.com/byu-oit-appdev/handel-account-configs/commit/0590eba278913d1afc9f31101985a5e29e122bfd).

**Comment by dsw88** [comment]
There was a bug in Handel-codepipelin that I fixed yesterday that should resolve this issue. Try running "npm install -g handel-codepipeline" to get the latest version and then try again.

**Comment by pauldeden** [comment]
Actually I ran npm install -g handel-codepipeline today.  Is there a way to
determine what version I have?

**Comment by pauldeden** [comment]
I just ran `sudo npm uninstall -g handel-codepipeline` and then `sudo npm install -g handel-codepipeline`.

Then I ran `handel-codepipeline` again and got the same error.

**Comment by dsw88** [comment]
Hmm that's odd, the error looks like you're running on an old version, I'll take a look at it some more.

**Comment by dsw88** [comment]
I believe I found the cause of the issue and fixed it. Try installing the latest version of handel-codepipeline from NPM and try again.

**Comment by pauldeden** [comment]
Confirmed fixed.  Thanks!
